[versions]
lombok = "1.18.42"
shadow = "9.3.0"
logback = "1.5.22"
jansi = "2.4.2"
fabric-loom = "1.14-SNAPSHOT"
fabric-loader = "0.18.2"
minecraft = "1.21.10"

[libraries]
# Common
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }


[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }